//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.SatisSistemi.IsMantigi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POS.SatisSistemi.IsMantigi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string AdSoyad {
            get {
                return ResourceManager.GetString("AdSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS - Point of Sale.
        /// </summary>
        public static string AnaFormBasliq {
            get {
                return ResourceManager.GetString("AnaFormBasliq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Inventory.
        /// </summary>
        public static string Anbar {
            get {
                return ResourceManager.GetString("Anbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Management.
        /// </summary>
        public static string AnbarFormBasliq {
            get {
                return ResourceManager.GetString("AnbarFormBasliq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        public static string Artikul {
            get {
                return ResourceManager.GetString("Artikul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by SKU/Barcode....
        /// </summary>
        public static string Axtar {
            get {
                return ResourceManager.GetString("Axtar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Barcode.
        /// </summary>
        public static string Barkod {
            get {
                return ResourceManager.GetString("Barkod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery instructions have been sent to {0}..
        /// </summary>
        public static string BərpaMesajı {
            get {
                return ResourceManager.GetString("BərpaMesajı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the e-mail address you registered with. Recovery instructions will be sent to that address..
        /// </summary>
        public static string BərpaTəlimatı {
            get {
                return ResourceManager.GetString("BərpaTəlimatı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Total.
        /// </summary>
        public static string Cəm {
            get {
                return ResourceManager.GetString("Cəm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        public static string GirişEt {
            get {
                return ResourceManager.GetString("GirişEt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password!.
        /// </summary>
        public static string GirişXətası {
            get {
                return ResourceManager.GetString("GirişXətası", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Send.
        /// </summary>
        public static string Göndər {
            get {
                return ResourceManager.GetString("Göndər", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string İstifadəçiAdı {
            get {
                return ResourceManager.GetString("İstifadəçiAdı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username already exists. Please choose a different one..
        /// </summary>
        public static string İstifadəçiAdıMövcuddur {
            get {
                return ResourceManager.GetString("İstifadəçiAdıMövcuddur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found registered with this e-mail address..
        /// </summary>
        public static string İstifadəçiTapılmadı {
            get {
                return ResourceManager.GetString("İstifadəçiTapılmadı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Kartla {
            get {
                return ResourceManager.GetString("Kartla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Köçürmə {
            get {
                return ResourceManager.GetString("Köçürmə", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LəğvEt {
            get {
                return ResourceManager.GetString("LəğvEt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Login.
        /// </summary>
        public static string LoginFormBasliq {
            get {
                return ResourceManager.GetString("LoginFormBasliq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Product Name.
        /// </summary>
        public static string MəhsulAdı {
            get {
                return ResourceManager.GetString("MəhsulAdı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Product.
        /// </summary>
        public static string MəhsulRedakteFormBasliq {
            get {
                return ResourceManager.GetString("MəhsulRedakteFormBasliq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Məlumat {
            get {
                return ResourceManager.GetString("Məlumat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miqdar.
        /// </summary>
        public static string Miqdar {
            get {
                return ResourceManager.GetString("Miqdar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Quantity.
        /// </summary>
        public static string MövcudMiqdar {
            get {
                return ResourceManager.GetString("MövcudMiqdar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cash.
        /// </summary>
        public static string Nəğd {
            get {
                return ResourceManager.GetString("Nəğd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Nisyə {
            get {
                return ResourceManager.GetString("Nisyə", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string ÖdənişNövü {
            get {
                return ResourceManager.GetString("ÖdənişNövü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Qeydiyyat {
            get {
                return ResourceManager.GetString("Qeydiyyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Registration.
        /// </summary>
        public static string QeydiyyatFormBasliq {
            get {
                return ResourceManager.GetString("QeydiyyatFormBasliq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration completed successfully!.
        /// </summary>
        public static string QeydiyyatUğurlu {
            get {
                return ResourceManager.GetString("QeydiyyatUğurlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Price.
        /// </summary>
        public static string Qiymət {
            get {
                return ResourceManager.GetString("Qiymət", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Satış_Tarixçəsi {
            get {
                return ResourceManager.GetString("Satış Tarixçəsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Transactions.
        /// </summary>
        public static string SatışƏməliyyatları {
            get {
                return ResourceManager.GetString("SatışƏməliyyatları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale ID.
        /// </summary>
        public static string SatışID {
            get {
                return ResourceManager.GetString("SatışID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Details.
        /// </summary>
        public static string SatışınTərkibi {
            get {
                return ResourceManager.GetString("SatışınTərkibi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales History.
        /// </summary>
        public static string SatışTarixçəsi {
            get {
                return ResourceManager.GetString("SatışTarixçəsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales History.
        /// </summary>
        public static string SatışTarixçəsiFormBasliq {
            get {
                return ResourceManager.GetString("SatışTarixçəsiFormBasliq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale completed successfully!.
        /// </summary>
        public static string SatışUğurluOldu {
            get {
                return ResourceManager.GetString("SatışUğurluOldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Password.
        /// </summary>
        public static string Şifrə {
            get {
                return ResourceManager.GetString("Şifrə", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        public static string ŞifrəBərpaFormBasliq {
            get {
                return ResourceManager.GetString("ŞifrəBərpaFormBasliq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string ŞifrələrEyniDeyil {
            get {
                return ResourceManager.GetString("ŞifrələrEyniDeyil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Forgot password.
        /// </summary>
        public static string ŞifrəmiUnutdum {
            get {
                return ResourceManager.GetString("ŞifrəmiUnutdum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ŞifrəTəkrar {
            get {
                return ResourceManager.GetString("ŞifrəTəkrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Are you sure you want to delete?.
        /// </summary>
        public static string SilməkİstədiyinizəƏminsiniz {
            get {
                return ResourceManager.GetString("SilməkİstədiyinizəƏminsiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Tarix {
            get {
                return ResourceManager.GetString("Tarix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAND TOTAL:.
        /// </summary>
        public static string ÜmumiYekun {
            get {
                return ResourceManager.GetString("ÜmumiYekun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unit Price.
        /// </summary>
        public static string VahidinQiyməti {
            get {
                return ResourceManager.GetString("VahidinQiyməti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be filled..
        /// </summary>
        public static string XanalarıDoldurun {
            get {
                return ResourceManager.GetString("XanalarıDoldurun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Xəbərdarlıq {
            get {
                return ResourceManager.GetString("Xəbərdarlıq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Amount.
        /// </summary>
        public static string YekunMəbləğ {
            get {
                return ResourceManager.GetString("YekunMəbləğ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Product.
        /// </summary>
        public static string YeniMəhsul {
            get {
                return ResourceManager.GetString("YeniMəhsul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add products to the cart..
        /// </summary>
        public static string ZəhmətOlmasaMəhsulSeçin {
            get {
                return ResourceManager.GetString("ZəhmətOlmasaMəhsulSeçin", resourceCulture);
            }
        }
    }
}
